package com.smartflowtech.cupidcustomerapp.ui.theme

import androidx.compose.ui.graphics.Color

val darkBlue = Color(0xFF001B6A)
val smartFlowBlue = Color(0xFF1F387C)
val black = Color(0xFF000C23)
val grey = Color(0xFF666666)
val lightGrey = Color(0xFFF6F7F9)
val lineGrey = Color(0xFFCFCED1)
val purple = Color(0xFF6941C6)
val gradientBluePurple = listOf(smartFlowBlue, purple)
val gradientWhiteBlue = listOf(Color.Transparent, darkBlue)
val skyBlue = Color(0xFFDBE5FD)
val brightBlue = Color(0xFF1890FF)
val indicatorGreyInactive = Color(0x4DD9D9D9)
val indicatorGreyActive = Color(0xFFD9D9D9)
val brightGreen = Color(0xFF17E7B5)
val pink = Color(0xFFF7DCFB)
val blue = Color(0xFF00B4D8)
val transparentBlue = Color(0xFFE1FAFF)
val green = Color(0xFF118569)
val transparentGreen = Color(0xFFCEFFF3)
val transparentPurple = Color(0xFFF6EBFF)
val yellow = Color(0xFFF3C583)
val transparentYellow = Color(0xFFFEFAE0)
val transparentPink = Color(0xFFFFEBEB)
val transparentAsh = Color(0xFFD9D9D9)
